# Generated by Django 4.2.3 on 2023-07-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squadra1', models.CharField(max_length=100)),
                ('squadra2', models.CharField(max_length=200)),
                ('goal1', models.IntegerField()),
                ('goal2', models.IntegerField()),
                ('falli1', models.IntegerField()),
                ('falli2', models.IntegerField()),
            ],
        ),
    ]
