# Generated by Django 4.2.3 on 2023-07-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partita',
            name='falli1',
        ),
        migrations.RemoveField(
            model_name='partita',
            name='falli2',
        ),
    ]
